#!/bin/bash

# Calculate new orientation
reorient() {
    local currentOrientation=$1
    local turnDirection=$2

    if test $turnDirection = 'L'; then
        case $orientation in
            'N')
                echo "W"
            ;;

            'E')
                echo "N"
            ;;

            'S')
                echo "E"
            ;;

            'W')
                echo "S"
            ;;
        esac
    else
        case $orientation in
            'N')
                echo "E"
            ;;

            'E')
                echo "S"
            ;;

            'S')
                echo "W"
            ;;

            'W')
                echo "N"
            ;;
        esac
    fi
}

main() {
    local -r INPUT="../data/input"

    # Read in list of directions
    local -a directions=( $(cat $INPUT | tr -d ' ' | tr ',' '\n') )

    local orientation='N'
    local -i posX=0
    local -i posY=0
    local -A positions=( ["0,0"]=1 )

    # Loop through each direction
    for direction in ${directions[@]}; do
        local -i magnitude=$(echo $direction | tr -d '[A-Z]')
        local turnDirection=$(echo $direction | tr -d '[0-9]')

        orientation=$(reorient $orientation $turnDirection)

        # We now need to know every point we pass though
        for ((index=0; index<magnitude; ++index)); do
            case $orientation in
                'N')
                    ((++posY))
                ;;

                'E')
                    ((++posX))
                ;;

                'S')
                    ((--posY))
                ;;

                'W')
                    ((--posX))
                ;;
            esac

            # Maintain an array of every point and compare against it at each step
            for position in ${!positions[@]}; do
                if test $position = "${posX},${posY}"; then
                    echo "Easter Bunny HQ is at $posX, $posY. Distance is $((posX + posY))"

                    exit 0
                fi
            done

            positions["${posX},${posY}"]=1
        done
    done
}

main "$@"
