#!/bin/bash

main() {
    local -r INPUT="../data/input"

    local -r ROOM_TO_FIND="northpole object storage"

    while read line; do
        local letters=$(echo $line | cut -d'[' -f1 | tr -d "0-9-")
        local checksum=$(echo $line | awk -F'-' '{print $NF}' | cut -d'[' -f2 | tr -d ']')
        local -i sectorNum=$(echo $line | awk -F'-' '{print $NF}' | cut -d'[' -f1)
        local -A charCounts

        # Get counts of characters
        for char in {a..z}; do
            charCounts[$char]=$(echo $letters | tr -dc $char | wc -m)
        done

        # Calculate what the true checksum should be
        local trueChecksum=$(for char in {a..z}; do
                                 echo "${charCounts[$char]} $char"
                             done | sort -k1,1nr -k2 | head -n 5 | cut -d' ' -f2 | tr -d '\n')

        # Test if the checksum is correct
        if test "$checksum" = "$trueChecksum"; then
            local roomName=$(echo $line | cut -d'[' -f1 | tr -d "0-9" | tr '-' ' ')

            # Performs shifts
            for ((index=0; index<sectorNum; ++index)); do
                roomName=$(echo $roomName | tr "a-z" "b-za")
            done

            echo -n "Decrypted room name \"$roomName\", sector id=$sectorNum : "

            if test "$roomName" = "$ROOM_TO_FIND"; then
                echo "Match found"
                exit
            else
                echo "No match"
            fi
        fi
    done < "$INPUT"
}

main "$@"
