#!/bin/bash

main() {
    local -r INPUT="../data/input"

    local -i sectorSum=0

    while read line; do
        local letters=$(echo $line | cut -d'[' -f1 | tr -d "[0-9]-")
        local checksum=$(echo $line | awk -F'-' '{print $NF}' | cut -d'[' -f2 | tr -d ']')
        local -i sectorNum=$(echo $line | awk -F'-' '{print $NF}' | cut -d'[' -f1)
        local -A charCounts

        #echo "letters=\"$letters\""
        #echo "sectorNum=\"$sectorNum\""
        #echo "checksum=\"$checksum\""

        # Get counts of characters
        for char in {a..z}; do
            charCounts[$char]=$(echo $letters | tr -dc $char | wc -m)
        done

        # Calculate what the true checksum should be
        local trueChecksum=$(for char in {a..z}; do
                                 echo "${charCounts[$char]} $char"
                             done | sort -k1,1nr -k2 | head -n 5 | cut -d' ' -f2 | tr -d '\n')

        #echo "trueChecksum=\"$trueChecksum\""

        # Test of the checksum is correct
        if test "$checksum" = "$trueChecksum"; then
            echo "\"$line\" is good"
            ((sectorSum += sectorNum))
        else
            echo "\"$line\" is bad"
        fi
    done < "$INPUT"

    echo "Sum of real sector numbers is $sectorSum"
}

main "$@"
