#!/usr/bin/env bash

testForAba() {
    local -r test="$1"

    for ((index=0; index<${#test} - 2; ++index)); do
        local a=${test:$index:1}
        local b=${test:$((index + 1)):1}

        if test $a != $b -a \
                $a = ${test:$((index + 2)):1}; then
            echo "${a}${b}${a}"
        fi
    done
}

testForbab() {
    local -r test="$1"
    local -r aba="$2"
    local -r bab="${aba:1:1}${aba:0:1}${aba:1:1}"

    if [[ "$test" =~ $bab ]]; then
        return 0
    fi

    return 1
}

main() {
    local -r INPUT="../data/input"

    local -i sslCount=0

    # Read all addresses
    while read address; do
        unset insideBrackets
        unset outsideBrackets

        local -a insideBrackets
        local -a outsideBrackets

        # Count brackets
        local -i numBrackets=$(echo $address | tr --delete --complement '[' | wc --chars)

        # Create arrays a values inside and outside of brackets
        for ((index=0; index<numBrackets; ++index)); do
            insideBrackets[$index]=$(echo $address | cut --delimiter=']' --fields=$((index + 1)) | cut --delimiter='[' --fields=2)
            outsideBrackets[$index]=$(echo $address | cut --delimiter='[' --fields=$((index + 1)) | cut --delimiter=']' --fields=2)
        done
        outsideBrackets[$numBrackets]=$(echo $address | cut --delimiter='[' --fields=$((numBrackets + 1)) | cut --delimiter=']' --fields=2)

        # Test for ABA outside of brackets
        for outside in ${outsideBrackets[@]}; do
            for aba in $(testForAba "$outside"); do
                # If ABA found then find BAB
                if test -n "$aba"; then
                    for inside in ${insideBrackets[@]}; do
                        if testForbab "$inside" "$aba"; then
                            echo "$address supports SSL"
                            ((++sslCount))
                            continue 4
                        fi
                    done
                fi
            done
        done
    
        echo "$address does not support SSL"
    done < "$INPUT"

    echo "$sslCount addresses support SSL"
}

main "$@"
